spring:
  jpa:
    show-sql: false

  kafka:
    bootstrap-servers: lendmate-kafka:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.lendmate.notification_service.kafka.OrderEvent

user-service:
  url: http://user-service:8081

product-service:
  url: http://product-service:8080