springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  forward-headers-strategy: framework

spring:
  application:
    name: notification-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: lendmate.pro@gmail.com
    password: hffhwylvlhvuxhtv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  kafka:
#    bootstrap-servers: localhost:9092 #lendmate-kafka:9092
#    consumer:
#      group-id: product-service
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer