springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  forward-headers-strategy: framework
  port: 8083

spring:
  application:
    name: notification-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: lendmate.pro@gmail.com
    password: hffhwylvlhvuxhtv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000 # max time to connect to smtp server
          timeout: 5000  # max time to wait response from server
          writetimeout: 5000  # max time to send mail context to server

management:
  endpoints:
    web:
      exposure:
        include: "*" # actuator / metrics / health endpointlerini dışarı açar
  metrics:
    tags:
      # Grafana dashboard'larının uygulamayı ayırt etmesi için service.name şarttır
      application: ${spring.application.name:order-service}
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.project: INFO